config/routes.rb
Rails.application.routes.draw do
  devise_for :devise_users
  # resources :users
  # resources :posts
  post "users/:id/update" => "users#update"
  get "users/:id/edit" => "users#edit"
  post "users/create" => "users#create"
  get "users/new" => "users#new"
  get "users/index" => "users#index"
  get "users/:id" => "users#show"
  get 'login' => 'users#login'
  post "login" => "users#login"

  get 'users/index'
  get 'posts' => 'posts#post'
  get 'posts/postslist' => 'posts#postslist'
  get 'posts/:id/edit' => 'posts#edit'
  get '/' => 'home#top'
  get 'home/profile' => 'home#profile'
  get 'posts/:id' => 'posts#show'

  post 'posts/create' => 'posts#create'
  post 'posts/:id/update' => 'posts#update'
  post 'posts/:id/destroy' => 'posts#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_devise_user!, except: [:top]
  def top
  end

  def prof
  end

  def login
  end

  def post
  end

  def postlist
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/profile.html.erb
<h1>プロフィールページ</h1>


<div class="profile-img"><%= image_tag current_devise_user.thumbnail %></div>

<div>自己紹介</div>

app/views/home/top.html.erb
<h1>トップページ</h1>

<h2>SNSアプリへようこそ</h2>
<div class="home-btn">
    <div class="btn"><%= link_to("新規登録", new_devise_user_registration_path) %></div>
    <div class="btn"><%= link_to("ログイン",devise_user_session_path) %></div>
</div>