config/routes.rb
Rails.application.routes.draw do
  devise_for :devise_users
  # resources :users
  # resources :posts
  post "users/:id/update" => "users#update"
  get "users/:id/edit" => "users#edit"
  post "users/create" => "users#create"
  get "users/new" => "users#new"
  get "users/index" => "users#index"
  get "users/:id" => "users#show"
  get 'login' => 'users#login'
  post "login" => "users#login"

  get 'users/index'
  get 'posts' => 'posts#post'
  get 'posts/postslist' => 'posts#postslist'
  get 'posts/:id/edit' => 'posts#edit'
  get '/' => 'home#top'
  get 'home/profile' => 'home#profile'
  get 'posts/:id' => 'posts#show'

  post 'posts/create' => 'posts#create'
  post 'posts/:id/update' => 'posts#update'
  post 'posts/:id/destroy' => 'posts#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SnsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='<%= "#{controller.controller_name}_#{controller.action_name}" %>'>
  <header>
    <div class="logo"><a href="/">logo</a></div>
    <nav>
      <ul class="header-menus">
        <li><%= link_to("プロフィール","/home/profile") %></li>
        <li><%= link_to("投稿","/posts") %></li>
        <li><%= link_to("投稿一覧","/posts/postslist") %></li>
        <li><%= link_to("ユーザー一覧","/users/index") %></li>
        <% if devise_user_signed_in? %>
          <li><%= link_to("ログアウト", destroy_devise_user_session_path, method: :delete )%></li>
          <li>ログイン中</li>
        <% else %>
          <li><%= link_to("新規登録", new_devise_user_registration_path) %></li>
          <li><%= link_to("ログイン",devise_user_session_path) %></li>
        <% end %>

      </ul>
    </nav>
  </header>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>